name: Deploy Multi-Environment Infrastructure
on:
  push:
    branches: [main]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev, staging, production)'
        required: true
        default: 'dev'
jobs:
  deploy_non_prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["dev", "staging"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
    - name: Terraform Init
      run: terraform init
      working-directory: environments/${{ matrix.env }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: environments/${{ matrix.env }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy_prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    permissions:
      issues: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
    - name: Terraform Init
      run: terraform init
      working-directory: environments/production
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Production Approval
      if: github.event_name == 'push'
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: ${{ secrets.APPROVERS }}  # Set this in Secrets (e.g., "your-username")
        minimum-approvals: 1
        issue-title: "Approve Production Deployment"
    - name: Terraform Apply (Production)
      if: github.event_name == 'workflow_dispatch' || steps.approval.outputs.approved == 'true'
      run: terraform apply -auto-approve
      working-directory: environments/production
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}